name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift package init --type executable
    - name: Run tests
      run: swift test -v
    - name: Build 2
      run: swift build
    - name: Upload artifact
      run: ls -R
